<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bunny.LibSql.Client" Version="0.9.6" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="11.0.0-preview.3.26207.106" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="bin\Debug\net9.0\appsettings.Development.json" />
      <Content Include="bin\Debug\net9.0\appsettings.json" />
      <Content Include="bin\Debug\net9.0\Microsoft.AspNetCore.OpenApi.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Configuration.Abstractions.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Configuration.Binder.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Configuration.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.DependencyInjection.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Diagnostics.Abstractions.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Diagnostics.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Http.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Logging.Abstractions.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Logging.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Options.ConfigurationExtensions.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Options.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.Extensions.Primitives.dll" />
      <Content Include="bin\Debug\net9.0\Microsoft.OpenApi.dll" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi.deps.json" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi.dll" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi.pdb" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi.runtimeconfig.json" />
      <Content Include="bin\Debug\net9.0\MtgToolsApi.staticwebassets.endpoints.json" />
      <Content Include="bin\Debug\net9.0\Nelknet.LibSQL.Bindings.dll" />
      <Content Include="bin\Debug\net9.0\Nelknet.LibSQL.Data.dll" />
      <Content Include="bin\Debug\net9.0\runtimes\linux-x64\native\libsql.so" />
      <Content Include="bin\Debug\net9.0\runtimes\osx-arm64\native\libsql.dylib" />
      <Content Include="bin\Debug\net9.0\runtimes\win-x64\native\libsql.dll" />
      <Content Include="bin\Debug\net9.0\runtimes\win-x86\native\libsql.dll" />
      <Content Include="bin\Release\net9.0\appsettings.Development.json" />
      <Content Include="bin\Release\net9.0\appsettings.json" />
      <Content Include="bin\Release\net9.0\Microsoft.AspNetCore.OpenApi.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Configuration.Abstractions.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Configuration.Binder.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Configuration.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.DependencyInjection.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Diagnostics.Abstractions.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Diagnostics.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Http.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Logging.Abstractions.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Logging.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Options.ConfigurationExtensions.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Options.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.Extensions.Primitives.dll" />
      <Content Include="bin\Release\net9.0\Microsoft.OpenApi.dll" />
      <Content Include="bin\Release\net9.0\MtgToolsApi" />
      <Content Include="bin\Release\net9.0\MtgToolsApi.deps.json" />
      <Content Include="bin\Release\net9.0\MtgToolsApi.dll" />
      <Content Include="bin\Release\net9.0\MtgToolsApi.pdb" />
      <Content Include="bin\Release\net9.0\MtgToolsApi.runtimeconfig.json" />
      <Content Include="bin\Release\net9.0\MtgToolsApi.staticwebassets.endpoints.json" />
      <Content Include="bin\Release\net9.0\Nelknet.LibSQL.Bindings.dll" />
      <Content Include="bin\Release\net9.0\Nelknet.LibSQL.Data.dll" />
      <Content Include="bin\Release\net9.0\runtimes\linux-x64\native\libsql.so" />
      <Content Include="bin\Release\net9.0\runtimes\osx-arm64\native\libsql.dylib" />
      <Content Include="bin\Release\net9.0\runtimes\win-x64\native\libsql.dll" />
      <Content Remove="obj\**" />
      <Content Remove="bin\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="obj\**" />
      <Compile Remove="bin\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="obj\**" />
      <EmbeddedResource Remove="bin\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="obj\**" />
      <None Remove="bin\**" />
      <None Include="Web.config">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
    </ItemGroup>

</Project>
